//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H15_Projet_E01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        public Agent()
        {
            this.Seances = new HashSet<Seance>();
        }
    
        public int AgentID { get; set; }
        public string Nom { get; set; }
    
        public virtual ICollection<Seance> Seances { get; set; }
    }
}
