//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H15_Projet_E01.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class H15_PROJET_E01Entities3 : DbContext
    {
        public H15_PROJET_E01Entities3()
            : base("name=H15_PROJET_E01Entities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agent> Agent { get; set; }
        public virtual DbSet<Facture> Facture { get; set; }
        public virtual DbSet<Forfait> Forfait { get; set; }
        public virtual DbSet<Notification> Notification { get; set; }
        public virtual DbSet<Photo> Photo { get; set; }
        public virtual DbSet<Photographe> Photographe { get; set; }
        public virtual DbSet<Seance> Seance { get; set; }
        public virtual DbSet<Statut> Statut { get; set; }
    }
}
