//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H15_Projet_E01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seance
    {
        public int SeanceID { get; set; }
        public Nullable<System.DateTime> DateSeance { get; set; }
        public string Adresse { get; set; }
        public string Ville { get; set; }
        public string Telephone { get; set; }
        public string Commentaire { get; set; }
        public int AgentID { get; set; }
        public string FactureID { get; set; }
        public Nullable<System.DateTime> HeureSeance { get; set; }
    
        public virtual Agent Agent { get; set; }
    }
}
